runtime: nodejs18
service: default
env: standard

handlers:
  - url: /.*
    script: auto

env_variables:
  PORT: 5000
  NODE_ENV: production
  # firebase config
  API_KEY: AIzaSyBl5pmzZiAqApUmQVtRW13fZWx2ugOoVNQ
  AUTH_DOMAIN: vinscan-3b689.firebaseapp.com
  PROJECT_ID: vinscan-3b689
  STORAGE_BUCKET: vinscan-3b689.appspot.com
  MESSAGING_SENDER_ID: 798378700635
  APP_ID: 1:798378700635:web:1781bbefae452b3b5cb47e
  MEASUREMENT_ID: G-HWDTWENFMM
